In [9]:
l=range(1000000)

In [2]:
import numpy as np

In [12]:
%time for i in range(1,10): r=[x*2 for x in l]

Wall time: 2.01 s


In [17]:
d=np.arange(1000000)

In [19]:
%time for i in range(1,10): r=d*2

Wall time: 102 ms


In [20]:
x=np.zeros((4,4))

In [21]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
y=np.ones((5,5))

In [23]:
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [26]:
l=[1,2,3,4,5]

In [27]:
np.array(l)

array([1, 2, 3, 4, 5])

In [30]:
x=np.arange(1,100,10)

In [31]:
x.shape

(10,)

In [38]:
x=np.zeros((10,10))


In [39]:
x.shape

(10, 10)

In [40]:
y=x.reshape((2,2,5,5))


In [41]:
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [42]:
y.dtype

dtype('float64')

In [44]:
x=np.random.randn(10)


In [45]:
y=np.random.randn(10)


In [46]:
x+y

array([ 0.29465365,  3.72336675, -1.33180422, -0.07557238,  2.22080232,
       -0.80407437, -0.65638502, -0.31296285, -0.19402859, -0.57887769])

In [47]:
x-y

array([ 1.53804368, -1.40580526,  0.57685044, -0.43688685,  1.22024132,
        0.99211441, -2.07648392,  2.32439559,  0.77425675,  2.03567855])

In [48]:
x*y


array([-0.56968939,  2.97179288,  0.36023651, -0.04628973,  0.86074352,
       -0.08443885, -0.97023605, -1.32621728, -0.14045661, -0.95222194])

In [49]:
x%y

array([-0.32704137,  1.15878074, -0.37747689,  0.10508485,  0.21968031,
       -0.80407437,  0.05366443, -0.31296285, -0.19402859, -0.57887769])

In [50]:
x>0

array([ True,  True, False, False,  True,  True, False,  True,  True,
        True])

In [52]:
x[x>0]

array([0.91634866, 1.15878074, 1.72052182, 0.09402002, 1.00571637,
       0.29011408, 0.72840043])

In [53]:
x[4]

1.7205218190891733

In [54]:
x=np.array([1,6,7,9,3])

In [55]:
x[x>5]

array([6, 7, 9])

In [56]:
x[[2,1]]

array([7, 6])

In [57]:
x=np.random.randn(10,10)

In [58]:
x

array([[ 0.0938853 , -0.51194103, -0.96858599,  0.29292657,  0.30871432,
        -0.65137676, -0.86909685, -0.15128003, -1.05327499,  0.48680685],
       [ 1.11378864,  1.32574316,  0.71279298,  2.02974028, -0.25016157,
         0.22499409, -0.54816511,  0.73233754,  2.1510427 , -0.41361301],
       [-1.69789582, -0.38212175,  0.18527519, -1.31804244,  0.47859598,
         0.99575759,  0.53304063, -1.11306043, -0.72950161,  0.65939763],
       [-1.52372588, -0.66390348,  1.29132306,  1.57720156, -1.1533944 ,
        -1.67368587,  0.10575844, -0.83633476,  0.63910949,  0.86163381],
       [ 0.12761565,  0.03717671,  0.6591219 ,  1.12147378,  0.50831124,
         0.54281309,  0.64943879, -0.87743792,  0.01388098,  1.04273116],
       [-2.76599486, -1.15962742,  0.83024857,  2.00315626,  2.08482857,
        -0.78182655,  0.25977005,  0.07965414, -1.43295678, -1.59809694],
       [ 0.70972186, -0.21216909, -0.83924021, -0.50322351,  1.00244135,
         2.06721655, -0.08534119,  0.06570825

In [59]:
x[0]

array([ 0.0938853 , -0.51194103, -0.96858599,  0.29292657,  0.30871432,
       -0.65137676, -0.86909685, -0.15128003, -1.05327499,  0.48680685])

In [60]:
x[0,5]

-0.6513767560424762

In [61]:
x[0][5]


-0.6513767560424762

In [62]:
x[1:10:2]

array([[ 1.11378864,  1.32574316,  0.71279298,  2.02974028, -0.25016157,
         0.22499409, -0.54816511,  0.73233754,  2.1510427 , -0.41361301],
       [-1.52372588, -0.66390348,  1.29132306,  1.57720156, -1.1533944 ,
        -1.67368587,  0.10575844, -0.83633476,  0.63910949,  0.86163381],
       [-2.76599486, -1.15962742,  0.83024857,  2.00315626,  2.08482857,
        -0.78182655,  0.25977005,  0.07965414, -1.43295678, -1.59809694],
       [-0.83841702,  0.22583348, -0.82142251, -0.50125374, -0.46184561,
        -1.98054184,  0.63022742, -0.99607897, -1.23749057, -2.41245551],
       [ 1.02503568,  0.31655925, -0.25220469, -1.1510077 , -0.24425189,
        -0.51408183,  0.06334431,  0.07956551, -0.21470527,  1.30660249]])

In [63]:
x[::,0:4]


array([[ 0.0938853 , -0.51194103, -0.96858599,  0.29292657],
       [ 1.11378864,  1.32574316,  0.71279298,  2.02974028],
       [-1.69789582, -0.38212175,  0.18527519, -1.31804244],
       [-1.52372588, -0.66390348,  1.29132306,  1.57720156],
       [ 0.12761565,  0.03717671,  0.6591219 ,  1.12147378],
       [-2.76599486, -1.15962742,  0.83024857,  2.00315626],
       [ 0.70972186, -0.21216909, -0.83924021, -0.50322351],
       [-0.83841702,  0.22583348, -0.82142251, -0.50125374],
       [ 0.52000986, -1.37204285, -1.03263568,  2.22748344],
       [ 1.02503568,  0.31655925, -0.25220469, -1.1510077 ]])

In [6]:
x=np.ones((10,10))

In [67]:
x[1:-1,1:-1]=0


In [68]:
x


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [124]:
x=np.ones((10,10))

In [125]:
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [131]:
for i in range(10): y=[]

In [132]:
y

3.0

In [3]:
np.__version__

'1.18.1'

In [4]:
np.__config__

<module 'numpy.__config__' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__config__.py'>

In [5]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 

In [7]:
x.ndim

2

In [8]:
np.array(range(10,30),dtype=bool)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [10]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
z=np.array([1,2,3,4,5])

In [13]:
z.dtype

dtype('int32')

In [14]:
z=np.array([1,2,3,4,5],dtype=float)

In [15]:
z.dtype

dtype('float64')

In [16]:
z

array([1., 2., 3., 4., 5.])